import { 
    MessageSquare, 
    FileText, 
    AlertCircle, 
    ImageIcon, 
    BarChart3, 
    BrainCircuit, 
    Award, 
    CheckCircle 
} from "lucide-react";

export const tasks = [
    {
      id: "hit-001",
      title: "Evaluate LLM Response Helpfulness (RLHF)",
      requester: "ESTARR Labs",
      reward: 1.50,
      baseRate: 1.00,
      bonus: 0.50,
      timeEstimate: "5 mins",
      type: "RLHF",
      category: "Text Analysis",
      icon: MessageSquare,
      color: "text-purple-600",
      bg: "bg-purple-100",
      description: "Read a prompt and two AI responses. Rate which response is more helpful, harmless, and honest.",
      progress: 40,
      autoApprove: true
    },
    {
      id: "hit-002",
      title: "Categorize Code Snippet Vulnerabilities",
      codeSnippet: "function authenticateUser(req, res) {\n  const query = 'SELECT * FROM users WHERE username = ' + req.body.username + ' AND password = ' + req.body.password;\n  db.execute(query);\n}",
      language: "javascript",
      requester: "SecurityAI Inc",
      reward: 3.00,
      baseRate: 2.00,
      bonus: 1.00,
      timeEstimate: "10 mins",
      type: "Annotation",
      category: "Text Analysis",
      icon: FileText,
      color: "text-blue-600",
      bg: "bg-blue-100",
      description: "Review Python and JavaScript code snippets and classify potential security vulnerabilities.",
      progress: 15,
      autoApprove: true
    },
    {
      id: "hit-003",
      title: "AI Audio Transcription Verification",
      requester: "VoiceTech Data",
      reward: 0.75,
      baseRate: 0.50,
      bonus: 0.25,
      timeEstimate: "2 mins",
      type: "Validation",
      category: "Audio Transcription",
      icon: AlertCircle,
      color: "text-amber-600",
      bg: "bg-amber-100",
      description: "Listen to a 10-second audio clip and correct any errors in the AI-generated transcription.",
      progress: 80,
      autoApprove: true,
      audioUrl: "https://actions.google.com/sounds/v1/alarms/digital_watch_alarm_long.ogg"
    },
    {
      id: "hit-004",
      title: "Rate Generated Image Quality",
      requester: "Visionary ML",
      reward: 0.50,
      baseRate: 0.40,
      bonus: 0.10,
      timeEstimate: "1 min",
      type: "RLHF",
      category: "Image Labeling",
      icon: ImageIcon,
      color: "text-rose-600",
      bg: "bg-rose-100",
      description: "Look at AI-generated images and rate them on a scale of 1-5 for photorealism and prompt alignment.",
      progress: 5,
      autoApprove: true
    },
    {
      id: "hit-005",
      title: "Developer Experience Tech Stack Poll",
      requester: "ESTARR Research",
      reward: 2.00,
      baseRate: 1.50,
      bonus: 0.50,
      timeEstimate: "4 mins",
      type: "Survey",
      category: "Survey",
      icon: BarChart3,
      color: "text-emerald-600",
      bg: "bg-emerald-100",
      description: "Answer a 10-question multiple choice survey regarding your preferred tech stacks and deployment tools.",
      progress: 70,
      autoApprove: true
    },
    {
      id: "hit-006",
      title: "AI Quality Analyst (Personalization) - Japanese",
      requester: "Global AI Insights",
      reward: 150.00,
      baseRate: 120.00,
      bonus: 30.00,
      timeEstimate: "4 hours",
      type: "Validation",
      category: "ML, Data & AI",
      icon: FileText,
      color: "text-indigo-600",
      bg: "bg-indigo-100",
      description: "Evaluate AI personalization quality using your personal experiences and insights.",
      progress: 0,
      autoApprove: false
    },
    {
      id: "hit-007",
      title: "Video Content Creator (US based)",
      requester: "Visuals Inc",
      reward: 150.00,
      baseRate: 100.00,
      bonus: 50.00,
      timeEstimate: "2 days",
      type: "Content Creation",
      category: "ML, Data & AI",
      icon: ImageIcon,
      color: "text-blue-600",
      bg: "bg-blue-100",
      description: "Create engaging walk-and-talk videos showcasing local public spaces.",
      progress: 0,
      autoApprove: false
    },
    {
      id: "hit-008",
      title: "LLM Trainer - Agent Function call",
      requester: "ESTARR Labs",
      reward: 150.00,
      baseRate: 150.00,
      bonus: 0.00,
      timeEstimate: "1 day",
      type: "RLHF",
      category: "ML, Data & AI",
      icon: MessageSquare,
      color: "text-purple-600",
      bg: "bg-purple-100",
      description: "Craft multi-turn dialogues to enhance AI assistant interactions.",
      progress: 0,
      autoApprove: true
    },
    {
      id: "hit-009",
      title: "Azure DevOps Engineer(LangGraph)",
      requester: "CloudScale",
      reward: 150.00,
      baseRate: 150.00,
      bonus: 0.00,
      timeEstimate: "1 day",
      type: "Engineering",
      category: "Software",
      icon: AlertCircle,
      color: "text-cyan-600",
      bg: "bg-cyan-100",
      description: "Build and optimize CI/CD pipelines for AI applications on Azure.",
      progress: 0,
      autoApprove: false
    },
    {
      id: "hit-010",
      title: "Dockerfile Data Validation Engineer",
      requester: "DataFlow Systems",
      reward: 150.00,
      baseRate: 125.00,
      bonus: 25.00,
      timeEstimate: "1 day",
      type: "Engineering",
      category: "Software",
      icon: CheckCircle,
      color: "text-teal-600",
      bg: "bg-teal-100",
      description: "Create and manage data-validation workflows in Docker-based build pipelines.",
      progress: 0
    },
    {
      id: "hit-011",
      title: "Software Engineer - AI Code Evaluation & Benchmarking (US candidates only)",
      requester: "ESTARR Labs",
      reward: 250.00,
      baseRate: 200.00,
      bonus: 50.00,
      timeEstimate: "2 days",
      type: "Evaluation",
      category: "Software",
      icon: Award,
      color: "text-rose-600",
      bg: "bg-rose-100",
      description: "Evaluate and improve AI-generated code for accuracy and quality.",
      progress: 0
    },
    {
      id: "hit-012",
      title: "Business Analyst (Finance)",
      requester: "FinTech Solutions",
      reward: 150.00,
      baseRate: 150.00,
      bonus: 0.00,
      timeEstimate: "1 day",
      type: "Analysis",
      category: "Finance",
      icon: BarChart3,
      color: "text-emerald-600",
      bg: "bg-emerald-100",
      description: "Evaluate finance model outputs and identify performance gaps.",
      progress: 0
    },
    {
      id: "hit-013",
      title: "JavaScript / TypeScript Full-Stack Developer",
      requester: "WebAI",
      reward: 150.00,
      baseRate: 120.00,
      bonus: 30.00,
      timeEstimate: "1 day",
      type: "Engineering",
      category: "Software",
      icon: FileText,
      color: "text-amber-600",
      bg: "bg-amber-100",
      description: "Develop and maintain high-quality JavaScript/TypeScript code for AI solutions.",
      progress: 0
    },
    {
      id: "hit-014",
      title: "Python + Full-Stack (JS) Developer",
      requester: "AI Innovators",
      reward: 150.00,
      baseRate: 130.00,
      bonus: 20.00,
      timeEstimate: "1 day",
      type: "Engineering",
      category: "Software",
      icon: FileText,
      color: "text-fuchsia-600",
      bg: "bg-fuchsia-100",
      description: "Develop and maintain high-quality code for AI model training and optimization.",
      progress: 0
    },
    {
      id: "hit-015",
      title: "Python Machine Learning Engineer",
      requester: "DeepMindful",
      reward: 150.00,
      baseRate: 150.00,
      bonus: 0.00,
      timeEstimate: "1 day",
      type: "Engineering",
      category: "ML, Data & AI",
      icon: BrainCircuit,
      color: "text-violet-600",
      bg: "bg-violet-100",
      description: "Own end-to-end development of machine learning solutions for business needs.",
      progress: 0
    },
    {
      id: "hit-016",
      title: "AI Quality Analyst - English",
      requester: "Global AI Insights",
      reward: 150.00,
      baseRate: 120.00,
      bonus: 30.00,
      timeEstimate: "4 hours",
      type: "Validation",
      category: "ML, Data & AI",
      icon: FileText,
      color: "text-indigo-600",
      bg: "bg-indigo-100",
      description: "Evaluate AI personalization quality using your personal experiences and insights.",
      progress: 0
    },
    {
      id: "hit-017",
      title: "Spanish Voice Actors (Studio-Grade Recording Experience)",
      requester: "LinguaTech",
      reward: 100.00,
      baseRate: 80.00,
      bonus: 20.00,
      timeEstimate: "3 hours",
      type: "Content Creation",
      category: "Audio Transcription",
      icon: AlertCircle,
      color: "text-orange-600",
      bg: "bg-orange-100",
      description: "Record engaging Spanish voice-overs for diverse projects from your studio.",
      progress: 0
    }
];
